<a href="https://colab.research.google.com/github/ritankarsaha/Automation/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

#Tensor -  A matrix or an Array
# They carry derivatives under the hood

a = torch.ones(5,6)
print(a)

# sum() and the mean() function

sum = torch.sum(a,axis =1) #for sum of rows
sum1 = torch.sum(a,axis=0) #for sum of columns
print(sum)
print(sum1)
mean =torch.mean(a,axis =0)
print(mean)


#squeeze() and unsqueeze() functions
b = torch.ones(5,1)
print(b.shape)
squeezed = torch.squeeze(b)
print(squeezed.shape)
print(squeezed.shape[0])

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([6., 6., 6., 6., 6.])
tensor([5., 5., 5., 5., 5., 5.])
tensor([1., 1., 1., 1., 1., 1.])
torch.Size([5, 1])
torch.Size([5])
5


In [ ]:
# defining a Neural Network Model in Pytorch
import torch
import torch.nn as nn
